### ISSUE TITLE
[feature request] /wiki/new - PATH field validation

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#12]
currently the only correct way to fill PATH field is like "/rules" which would properly generate new page

if user would fill it like "rules" the system would give him error "Could not create wiki page: That is not a valid path". this is a bit misleading since there's nowhere said that PATH should start with / symbol
if user would fill it like "/rules/" the system would create the page (so this adress would be taken) but other fields (TITLE and BODY) would not be saved and the pages would not be available for any alteration through the interface

i guess this could minimize negative user experience:
* make users fill PATH not from "wiki" but from "wiki/" so "rules" or "rules/old" would become correct way to fill PATH field
* auto trim / symbol in the end of PATH field if user enters it

**Comment by tdjsnelling** [comment]
Added more helpful handling in b6ae74fce7d17fbe73fbbf7a9a4caed46285d8ce.

Leading/trailing `/` will be handled automatically whether the user includes them or not. Paths will also now be formatted properly and stripped of non URL safe characters.
