### ISSUE TITLE
[feature request] torrent list ammendments

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#15]
1. Please consider adding column with number of downloads in the torrent list which is shown on the homepage and on categories pages.

2. Please consider making all columns of the torrent list on categories pages sortable.

**Comment by tdjsnelling** [comment]
1. 5eb4dd312f4b2eb7380d1e51253c8c6f0d1d22bc adds download count to all lists
2. edc5e8275f6f86b1240f94d591749f1ee7e5489b makes columns sortable in categories, tags, and search results
