### ISSUE TITLE
[feature request] file browser sorting ammendment

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#16]
Most torrent clients (not all as i guess) have an option on new torrent creation which is called "optimize file sorting". 
When this option is on, distributed files are put in torrent file in correct order, this results in posh presentation in file browser on torrent description page.
If this option is off or if torrent client doesn't have this option at all, distributed files would be put in torrent file in chaotic order, so presentation would be also chaotic.

Please compare:
https://utkonos.org/torrent/771454ea2a1761f146fa6c1c59fa3867b485124e (option is on, great view in file browser)
https://utkonos.org/torrent/21b73153e8405a776e9f9eb3324eb93c63905540 (option if off, file browser is messed up, both folder order and order of files within folders)

Please consider adding an option of additional sorting of file/folder records before presenting them in file browser in torrent description, so the order in file browser would be always correct, regardless of settings in original torrent file.

**Comment by tdjsnelling** [comment]
55606bb086608cbaab82ba18972dcd101bccb805
