### ISSUE TITLE
[feature request] file extensions blacklist

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#18]
Please consider adding file extensions blacklist (possibly, as an option in config file) so admin could set which files are forbidden to upload on tracker.

And if someone tries to upload torrent, which includes file with forbidden extension, system won't allow to upload this torrent and would show message that files with such extension are banned on this tracker.

So music/movie torrent trackers could ban all exe/dmg/bat/cmd etc for security reasons, lossless torrent trackers could ban all mp3/wma/aac and so on.

**Comment by tdjsnelling** [comment]
Added in [1.3.0](https://github.com/tdjsnelling/sqtracker/releases/tag/1.3.0)
