### ISSUE TITLE
[feature request] request fulfilling with URL

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#19]
Currently "suggest a torrent" form only accepts infohash to fulfill request.
Even for experienced user it's not obvious what he has to copy and where.
Please consider softening of validation rules, so user could fulfill request with either infohash or URL of torrent page.

**Comment by tdjsnelling** [comment]
This is fine imo, any tracker user should know what the infohash is and where to get it. The URL is just the infohash anyway, so if they can copy the URL they can copy the infohash.
