### ISSUE TITLE
[bug] fast column sorting

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#23]
1. User enters any screen with sortable grid
2. User clicks on "uploaded" column header 10+ times within few seconds

Current result: system redirects to ?sort=created%3Aasc and says "Something went wrong :("
Expected result: system shows list of sorted results on each click

**Comment by tdjsnelling** [comment]
This happens due to hitting the API rate limit if you spam the sorting. I have added a message on the error page to let the user know if this is the case.
