### ISSUE TITLE
[feature request] privacy settings for wiki pages

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#24]
Please consider adding an option in wiki page settings if it's open for unregistered view or not (with not as default)

For example, currently there is a page https://demo.sqtracker.dev/wiki/rules
But i can't view it before i sign up & sign in https://demo.sqtracker.dev/
This means that i'm able to view the rules only after i sign up and agree to them!

**Comment by tdjsnelling** [comment]
Also done in 73dda4cdca8b7fa4379e0e6864914040710c0e4e, out in next release
