### ISSUE TITLE
[bug] announcement autoreplace won't work if uploaded torrent have more than 1 announcement server

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#30]
Follow-up to https://github.com/tdjsnelling/sqtracker/issues/5

Currently when user uploads torrent file which has 1 foreign announcement server listed sqtracker automatically replaces this server with proper announcement URL.
And when user uploads torrent file which has 2 or more foreign announcement server listed sqtracker just uploads this file as is and adds/replaces nothing.

Please consider making sqtracker replace all announcement URLs on upload regardless of their quantity with actual URL.

**Comment by doomtop** [comment]
Seems like this functionality exists here: https://github.com/tdjsnelling/sqtracker/blob/master/api/src/controllers/torrent.js#L70-L71

But `parsed` version is not saved; instead unaltered original upload from `req.body` is saved: https://github.com/tdjsnelling/sqtracker/blob/master/api/src/controllers/torrent.js#L138

@tdjsnelling Did I misunderstand something here?

**Comment by tdjsnelling** [comment]
@doomtop You are correct, `parsed` should be bencoded and converted to base64 to be saved rather than saving the original upload, that is a mistake. I will merge https://github.com/tdjsnelling/sqtracker/pull/42 for now to fix the announce list issue.
