### ISSUE TITLE
[feature request] more clear error message on missing .torrent file

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#45]
If user fills all the fields of "upload torrent" form but doesn't choose .torrent file in TORRENT FILE selector, then on pressing "Upload" button system would show error message "Could not upload file: Cannot read properties of undefined (reading 'b64')".

This text is a bit misleading for users, please consider changing it for something like "Please choose .torrent file"

**Comment by tdjsnelling** [comment]
Solved in 1.3.1
