### ISSUE TITLE
Support for magnet links

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [tdjsnelling/sqtracker#47]
Are there any plans on supporting magnet links in the future instead of just `.torrent` files

**Comment by HEPOSHEIKKI** [comment]
After some research this seems very doable. The torrents are already identified by their hash so the magnet link can be generated with javascript on the spot. I tried implementing this myself and opening a PR but unfortunately I am not familiar with the framework you are using.

**Comment by tdjsnelling** [comment]
Magnet links do not really make sense in a private tracker as they cannot contain the private flag, meaning a torrent added via magnet link will always be added to the DHT, defeating the purpose of the private tracker. For this reason magnet links were removed from sqtracker.
