### ISSUE TITLE
[feature request] autoreplace announcement url upon torrent file uploading

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#5]
Currently when you try to upload torrent file which contains wrong announcement url; sqtracker sends you error "Could not upload file: Announce URL is invalid"

From UX perspective it seems more useful for uploader that sqtracker in this case should:
1. remove wrong announcement url from the file;
2. put correct announcement url from the file;
3. upload & register torrent without error;
so user won't have to regenerate torrent file himself.

**Comment by tdjsnelling** [comment]
Thanks, this is added in 1.1.0.
