### ISSUE TITLE
Download files over http(s)

### ISSUE THREAD

**Issue by Baklap4** [tdjsnelling/sqtracker#50]
# Feature request

I'd love to be able to download specific files from a torrent but not through a torrent but over http(s).

# Description

So yeah in short a torrent can have multiple files.
Within your torrent client you can define which files you want to download and which you don't want.
What i'd like to see is that this can also be done through the webbrowser itself so you just have a regular download.

My usecase being that 'torrenting' in general is seemed as illegal activity whereas downloading through the normal web is more acceptable to most endusers. Sure in both cases if the content is illegal you're doomed eitherway, but this saves the hassle of explaining it to the enduser. This makes it more of a download platform than just a torrent/p2p platform.

# Options
A couple of options can be implemented:
1. Download a singular file from a multi-file torrent
2. Download the content of the whole torrent, but over http (not sure if web-based client-sided programs exist...)

**Comment by tdjsnelling** [comment]
Thanks for your request. sqtracker is solely a bittorrent tracker platform, and there are no plans to support `server <-> client` downloads. sqtracker does not host or store any files, what you are looking for is an entirely different solution. Bittorrent is no more illegal than downloading files directly from a server – only the legality of the content matters.
