### ISSUE TITLE
[feature request] file browser ammendment

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#6]
Problem:
when you upload torrent, which contains a lot of folders and files, their list makes page too long
check https://demo.sqtracker.dev/torrent/0027b9df8f1a7ff500982a65feb7bfe86d4276f1

Solution:
each folder could be shown as spoiler, so files in this folder are shown only when user clicks on folder name (same as it's done in UNIT3D)

**Comment by tdjsnelling** [comment]
Thanks, this is added in 1.1.0.
