### ISSUE TITLE
[feature request] multilanguage support

### ISSUE THREAD

**Issue by utkonostracker** [tdjsnelling/sqtracker#8]
Currently all messages in the interface are hardcoded.

Please consider moving all interface messages to separate file so it would be possible to translate interface to other languages.

**Comment by tdjsnelling** [comment]
I have done the ground work to support this on the branch [feature/localisation](https://github.com/tdjsnelling/sqtracker/tree/feature/localisation). It is a pretty big job to move all of the hard coded strings to the locale file so would massively appreciate if yourself and others would be willing to contribute here.

`locales.json` contains a structure like this:

```json
{
  "en": {
    "logIn": "Log in"
  },
  "fr": {
    "logIn": "Se connecter"
  }
}

```

And then in the client the correct string for the current locale is fetched with:

```jsx
<Text>{getLocaleString("logIn")}</Text>
```

Switching locale in the menu and saving the preference to a cookie is already handled.

**Comment by ianlot** [comment]
Separated language files would be better, and easier to maintain.

**Comment by tdjsnelling** [comment]
Most of the work here is done now on the branch I mentioned above, which I will merge soon. All that remains now is for people to contribute their translations!

**Comment by pureGavin** [comment]
> Most of the work here is done now on the branch I mentioned above, which I will merge soon. All that remains now is for people to contribute their translations!

my holiday is comming, i will try to translate the zh.json, hopfully you merge it as quickly as possible when i finish it :p
