### ISSUE TITLE
Client doesn't seem to open

### ISSUE THREAD

**Issue by cmiamoe** [tdjsnelling/sqtracker#87]
Hi, I've deployed sqtracker via docker, opened the port for it, but my browser doesn't really want to open the client interface on http://10.0.0.x:3000

Api and mongo started succesfully
Api logs:
```
yarn run v1.22.19
$ babel-node src/index.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[sq] configuration is valid
[sq] initiating db connection...
[sq] ■ sqtracker running http://localhost:3001
[sq] connected to mongodb successfully
```
Client logs:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

It says ready, but it doesn't really want to open on it's network ip

**Comment by Klaiment** [comment]
hi !
send Screenshot of `docker ps`
same problem with localhost:3000 ?
u have configured the config.js

**Comment by cmiamoe** [comment]
I have fixed it by setting email server, weird.
